### ISSUE TITLE
Missing "./dist/runtime/client" export in "trpc-nuxt" package  

### ISSUE THREAD

**Issue by cawa-93** [wobsoriano/trpc-nuxt#11]
In v0.2 I got error when tried build:
```
 ERROR  [vite:resolve] Missing "./dist/runtime/client" export in "trpc-nuxt" package                                                                                        11:53:00  


 ERROR  Missing "./dist/runtime/client" export in "trpc-nuxt" package                                                                                                       11:53:00  

  at bail (node_modules/vite/dist/node/chunks/dep-8f5c9290.js:38572:8)
  at resolve (node_modules/vite/dist/node/chunks/dep-8f5c9290.js:38649:10)
  at resolveExports (node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40957:12)
  at resolveDeepImport (node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40975:31)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40748:20)
  at Object.resolveId (node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40556:28)
  at node_modules/rollup/dist/shared/rollup.js:22868:37
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by cawa-93** [comment]
Never mind. I'm idiot 🤦‍♂️
