### ISSUE TITLE
Failed to find composables imported from "#imports" in v0.3

### ISSUE THREAD

**Issue by cawa-93** [wobsoriano/trpc-nuxt#48]
```node
> nuxt build

Nuxi 3.0.0                                                                                                                                  15:24:48
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                 15:24:48
✔ Plugin successfully installed.                                                                                                  trpc-nuxt 15:24:48

 ERROR  [nuxt:imports-transform] [unimport] failed to find "useAsyncQuery" imported from "#imports"                                         15:24:57
file: /home/cawa-93/dev/kitlink/pages/cabinet/pixels.vue?vue&type=script&setup=true&lang.ts


 ERROR  [unimport] failed to find "useAsyncQuery" imported from "#imports"                                                                  15:24:57

  at node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:782:17
  at Array.forEach (<anonymous>)
  at node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:779:44
  at Array.forEach (<anonymous>)
  at detectImports (node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:777:20)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async injectImports (node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:804:44)
  at async Object.transform (node_modules/nuxt/dist/index.mjs:1107:21)
  at async transform (node_modules/rollup/dist/es/shared/rollup.js:21734:16)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:21959:30)


Process finished with exit code 1
```
```node
> nuxt dev
                                                                                                                                                             15:31:53
Nuxi 3.0.0                                                                                                                                                   15:31:53
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                                  15:31:53
                                                                                                                                                             15:31:55
  > Local:    http://localhost:3000/ 
  > Network:  http://172.29.134.12:3000/                                                                                                                     15:31:53

✔ Plugin successfully installed.                                                                                                                   trpc-nuxt 15:31:55

 ERROR  [unimport] failed to find "useClient" imported from "#imports"                                                                                       15:32:03
 ERROR  [unimport] failed to find "useAsyncQuery" imported from "#imports"                                                                                   15:32:03
 ERROR  [unimport] failed to find "getQueryKey" imported from "#imports"                                                                                     15:32:04
 ERROR  [unimport] failed to find "getQueryKey" imported from "#imports"                                                                                     15:32:04
 ERROR  [unimport] failed to find "useClient" imported from "#imports"                                                                                       15:32:04
 ERROR  [unimport] failed to find "getQueryKey" imported from "#imports"                                                                                     15:32:04
 ERROR  [unimport] failed to find "useClient" imported from "#imports"                                                                                       15:32:04
```

Nuxt 3.0.0 and trpc-nuxt v0.3.3

Nuxt config:
```ts
import { defineNuxtConfig } from 'nuxt/config'
import { runtimeConfig } from './config/runtimeConfig'

export default defineNuxtConfig({
  telemetry: process.dev,

  dir: {
    pages: process.env.NUXT_PAGES_ROOT || 'pages',
  },

  modules: ['trpc-nuxt'],

  typescript: {
    strict: true,
  },

  runtimeConfig: runtimeConfig,
  css: [ 'assets/styles/bootstrap.scss', ],

  build: { transpile: ['chart.js'], },
})
```

All works on nuxt 3.0.0-rc.11, but doesn't work in nuxt 3.0.0-rc.14 or 3.0.0

**Comment by wobsoriano** [comment]
Fixed in 0.3.7. Thanks!
